(require 'org-octopress)
(setq org-octopress-directory-top       "~/octopress/source")
(setq org-octopress-directory-posts     "~/octopress/source/_posts")
(setq org-octopress-directory-org-top   "~/octopress/source")
(setq org-octopress-directory-org-posts "~/octopress/source/blog")
(setq org-octopress-setup-file          "~/org-sty/setupfile.org")
;; (setq org-jekyll-comments t)
